## throws
*throws*:throws是用来声明一个方法可能抛出的所有异常信息，throws是将异常声明但是不处理，而是将异常往上传，谁调用我就交给谁处理。

*throws*：用于声明异常，例如，如果一个方法里面不想有任何的异常处理，则在没有任何代码进行异常处理的时候，必须对这个方法进行声明有可能产生的所有异常（其实就是，不想自己处理，那就交给别人吧，告诉别人我会出现什么异常，报自己的错，让别人处理去吧）。

格式是：方法名（参数）throws 异常类1，异常类2，.....

```Java
import java.util.Scanner;

public class TestThrows{
    // 自己不处理异常，而是让异常往上抛，让调用该函数的处理异常
    static double test(int num) throws Exception{
        int i = 10;
        i = i / num;
        return i;
    }

    public static void main(String[] args) {
        Scanner in  = new Scanner(System.in);
        int num = in.nextInt();
        try{
            double a = test(num);
            System.out.println("值:"+a);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
}
```

## throw
*throw*：就是自己进行异常处理，处理的时候有两种方式，要么自己捕获异常（也就是try catch进行捕捉），要么声明抛出一个异常（就是throws 异常~~）。

*注意*：throw一旦进入被执行，程序立即会转入异常处理阶段，后面的语句就不再执行，而且所在的方法不再返回有意义的值！

```Java
public class TestThrow{
    public static void throwChecked(int a) throws Exception{
        if( a > 0){
            throw new Exception("值大于0，不符合要求！");
        }
    }

    public static void throwRunTime(int a){
        if( a > 0){
            throw new RuntimeException("a的值大于0，不符合要求");
        }
    }
    public static void main(String[] args) {
        // 调用throws声明的方法，必须显式的捕获该异常。
        // 否则必须在该方法再次抛出，让其他调用该方法的方法处理异常。
        try {
            throwChecked(-3);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        // 调用RunTime异常的方法既可以显式捕获该异常，也可以不理会该异常。
        throwRunTime(3);
        
        // 显式的处理该异常
        try {
            throwRunTime(4);
        }catch (RuntimeException e){
            System.out.println(e.getMessage());
        }
    }
}
```

## 异常
*异常分类*：Java把异常当对象处理，`java.lang.Throwable`作为所有异常的超类。Java的异常分为两大类：错误Error和异常Exception。Exception分为运行时异常和非运行时异常。

### 可查异常（非运行时异常）
*可查异常*：可查异常即必须处理的异常，要么try catch处理，要么往外抛，谁调用，谁处理。如果不处理，编译器不通过。比如`FileNotFoundException`。

### 运行时异常
*运行时异常RuntimeException指*： 不是必须进行try catch的异常，它描述的是程序设计错误。

常见运行时异常: 
- 除数不能为0异常:ArithmeticException 
- 下标越界异常:ArrayIndexOutOfBoundsException 
- 空指针异常:NullPointerException 

在编写代码的时候，依然可以使用try catch throws进行处理，与可查异常不同之处在于，即便不进行try catch，也不会有编译错误。Java之所以会设计运行时异常的原因之一，是因为下标越界，空指针这些运行时异常太过于普遍，如果都需要进行捕捉，代码的可读性就会变得很糟糕。

### 错误
*错误Error*：指的是系统级别的异常，通常是内存用光了
在默认设置下，一般java程序启动的时候，最大可以使用16m的内存，如例不停的给StringBuffer追加字符，很快就把内存使用光了。抛出OutOfMemoryError。

与运行时异常一样，错误也是不要求强制捕捉的

### 运行时异常和非运行时异常区别
- 运行时异常都是RuntimeException类以及其子类的异常，运行时异常在编写代码时既可以用try catch捕获，也可以不处理，编译不会出错，常见的运行时异常有除数为0，下标越界，
空指针异常。出现运行时异常后，如果没有捕获处理这个异常（即没有catch），系统会把异常一直往上层抛，一直到最上层，如果是多线程就由Thread.run()抛出，如果是单线程就被main()抛出。抛出之后，如果是线程，这个线程也就退出了。如果是主程序抛出的异常，那么这整个程序也就退出了。运行时异常是Exception的子类，也有一般异常的特点，是可以被catch块处
理的。只不过往往我们不对他处理罢了。也就是说，你如果不对运行时异常进行处理，那么出现运行时异常之后，要么是线程中止，要么是主程序终止。

- 非运行时异常是RuntimeException以外的异常，类型上都属于Exception类及其子类。如IOException、SQLException等以及用户自定义的Exception异常。对于这种异常，JAVA编译器强制要求我们必需对出现的这些异常进行catch并处理，否则程序就不能编译通过。所以，面对这种异常不管我们是否愿意，只能自己去写一大堆catch块去处理可能的异常。
